# Generated by Django 5.2 on 2025-05-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='movie',
            field=models.IntegerField(unique=True),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='added_at',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
