# Generated by Django 5.2 on 2025-05-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_watchlist_movie_remove_watchlist_added_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='movie',
            field=models.IntegerField(),
        ),
    ]
